name: Solar and Battery Power Australia
analytics: {}
github: true
description: We help Australians make the switch to Solar & Battery Power today.
author:
  name: Laurence Henderson
  url: 'https://powur.com/laurence.henderson/getsolar'
  email: sunnygreensolar@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.1874048486351967
color:
  lightness: 0.4569132366350184
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  saturation: 0.709670064437592
  brandStrength: 0.4614209019256339
  rhythmicContrast: 0.0725941476581139
content_rating:
  adult: false
typography_spectrum: 0.7997081154026091
opengraph: {}
title: Solar and Battery Power Australia
