layout_spectrum: 0.5906062986610439
typography_spectrum: 0.1942744141145803
color:
  lightness: 0.784239248909462
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  saturation: 0.9786484827875795
  brandStrength: 0.6355874017283948
  rhythmicContrast: 0.2798863817788292
coverPrefs:
  filter: false
name: Solar and Battery Power Australia
analytics: {}
github: true
description: We help Australians make the switch to Solar & Battery Power today.
author:
  name: Laurence Henderson
  url: 'https://powur.com/laurence.henderson/getsolar'
  email: sunnygreensolar@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
title: Solar and Battery Power Australia
